### ISSUE TITLE
metadata for start and flush

### ISSUE THREAD

**Issue by fippo** [w3c/webrtc-encoded-transform#10]
related to #9 

Some things like the SSRC are constant over the lifetime of the stream (well, modulo ssrc changes...).

It would be useful to avoid first-time-initialization bookkeeping along the lines of "we haven't seen this ssrc" inside the main transform function. Same for flush, there one could still do periodic cleanup but that is even worse

**Comment by fippo** [comment]
The concrete example is using a per-ssrc counter starting at a random offset

**Comment by murillo128** [comment]
this should only be needed if simulcast is multiplexed over the same pair of streams, rigth?

**Comment by fippo** [comment]
even then I might want to generate a random start offset. Can be done as a bound function when creating the transform stream arguably.

**Comment by alvestrand** [comment]
I've had thought about having a "control" frame (new type field) and have "controls" for start, mute and unmute events. Possibly also encoder reconfig "for info".

This becomes even more relevant if we start adding a feedback channel; all the stuff that goes there would be "control".

**Comment by fippo** [comment]
Given that everyone had to implement the "ugly variant" already I don't think solving this will provide much value
