### ISSUE TITLE
Should there be a RTCConfiguration boolean to prevent data to be sent without being transformed

### ISSUE THREAD

**Issue by youennf** [w3c/webrtc-encoded-transform#104]
encodedInsertableStreams=true has the benefit that a web app is sure that no data will be sent before its transforms are ready. This might be a nice safety belt, so I am wondering whether this is something the transform API should expose or not.
Instead of buffering data, I would tend to just drop data on the floor.
There are some potential alternatives (sender active) so this might not be strictly needed but might still come handy.

**Comment by alvestrand** [comment]
I understood the "new" transform API to automagically preserve this property because the creation of the streams occured in a task that was enqueued previous to any possible user event. If I misunderstood the API, we do need some other safeguard.

**Comment by youennf** [comment]
Web developers if they set the transform synchronously at creation time should not have any frame going untransformed.
Ditto if they change the transform from one to another synchronously.
If web developers do sender.transform = transform1;sender.transform=null;sender.transform=transform2, some frames might get untransformed.

The question I am asking is whether we should add an additional API =to change the behavior of the default transform (when none is set). For instance from passthrough to dropall (I do not really like the idea of buffer all like the old API was doing).

I would lean towards no API.

**Comment by alvestrand** [comment]
Aha - you are thinking about the case where one changes the transform after creation of the sender/receiver.

This involves ending the original stream, creating new streams, signalling them and ensuring that frames end up in the right place. And defining what happens if you set the transform to null.

1) Do we have legitimate use cases for this functionality?
2) If no, is there a decent way to say ".transform has to be set before sender/receiver is fully activated, and is read-only thereafter"?

**Comment by youennf** [comment]
The other case I am thinking of is:
sender = pc.addTrack(...)
sender.transform = new RTCRtpScriptTransform(worker, { parameters : await myAsyncOperation() });

This is all fixable by web developers and they should really make sure to do that.

> 1. Do we have legitimate use cases for this functionality?

There could be some usecases though I am not sure how big they are.
For instance dynamically entering a record or screencast mode temporarily where encryption is dropped.
Or setting new SFrameTransform objects instead of changing the keys.

Spec (and prototype) already supports that usecase. It does add limited complexity in practice, thanks to the use of streams API.

> 2\. If no, is there a decent way to say ".transform has to be set before sender/receiver is fully activated, and is read-only thereafter"?

That is the alternative but I did not want to go there since it might not be very clear when it is r/w and when it is readonly.
Say the transceiver is inactive or recvonly. Or the sender active is false.

**Comment by fippo** [comment]
note that https://w3c.github.io/webrtc-encoded-transform/#operation currently talks about a "corresponding flag" in the configuration but doesn't define one.

**Comment by youennf** [comment]
Closing it since JS can implement this themselves by making sure to set the transform soon enough when the sender is active and attached to a track.
