### ISSUE TITLE
should it be possible to disable transforms on the fly?

### ISSUE THREAD

**Issue by fippo** [w3c/webrtc-encoded-transform#142]
from https://bugs.chromium.org/p/chromium/issues/detail?id=1347309

while I would 😍 to see this feature I think it is pretty hard to implement and does not offer much value over setting an identity transform.

Should we reject a change in the value using setConfiguration with a InvalidModificationError?
(also we seem to have lost the RTCConfiguration option somehow...)

**Comment by youennf** [comment]
@fippo, you are probably referring to Chrome current implementation which is based on an earlier draft of this spec.
Since then, we moved to a different model, which supports disabling transforms and does not require any RTCConfiguration option.

**Comment by fippo** [comment]
true, will add to #64
