### ISSUE TITLE
statistics

### ISSUE THREAD

**Issue by fippo** [w3c/webrtc-encoded-transform#15]
@emcho asked me some good questions about performance. This is measurable with performance.now() and then summing that up.

Should we have something similar to [totalEncodeTime](https://w3c.github.io/webrtc-stats/#dom-rtcoutboundrtpstreamstats-totalencodetime) to allow measuring how much time is spent in insertable streams?

**Comment by fippo** [comment]
made up my own, even though they're [a bit inaccurate by design](https://developer.mozilla.org/en-US/docs/Web/API/Performance/now)
![image](https://user-images.githubusercontent.com/289731/80942651-9da3b400-8de5-11ea-905f-9ec02bcff590.png)
So in the order of 0.4-0.5 milliseconds per frame.

Going from 640x480 to 720p  resolution lowers the time per frame so i'm probably running into the inaccuracy of performance.now() mentioned on mdn.

**Comment by alvestrand** [comment]
I think we should have totalInsertedProcessingTime for senders and receivers. And frame counters for number of frames that have exited processing.
Defined as elapsed time between frame-leaves-Webrtc-layer and frame-reenters-Webrtc-layer.
There are some weird cases (are you allowed to delay frames, for instance? What does that do to stats? Do we care?), but that seems to be the most useful metric for the 90% case.

**Comment by fippo** [comment]
do we also want the number of bytes the added?

**Comment by alvestrand** [comment]
I think we should make a PR on one of the stats docs, that can be merged once the WG has adopted this spec.

**Comment by alvestrand** [comment]
re number of bytes: I think we should count buffer bytes in and buffer bytes out.

**Comment by fippo** [comment]
I don't think we need them. totalProcessingTime (implemented since) might allow measuring the overhead
