### ISSUE TITLE
Expose MIME type as frame metadata

### ISSUE THREAD

**Issue by alvestrand** [w3c/webrtc-encoded-transform#158]
At the moment, payload type is exposed in metadata. But decoding this information needs a) access to SDP, and b) an SDP parser that can accurately identify the relevant MIME type.
The platform already knows the MIME type, so supplying it should be simple. This makes the API user's task easier, and seems to have little downside.

Use Case: https://w3c.github.io/webrtc-nv-use-cases/#auction

**Comment by aboba** [comment]
[Resolution from 10-18-2022 WG meeting](https://www.w3.org/2022/10/18-webrtc-minutes.html#t04): "Add mimeType to Metadata".
