### ISSUE TITLE
Clarify why the writable stream backpressure should be disabled

### ISSUE THREAD

**Issue by saschanaz** [w3c/webrtc-encoded-transform#188]
https://w3c.github.io/webrtc-encoded-transform/#stream-creation

>[Set up](https://streams.spec.whatwg.org/#writablestream-set-up) [this](https://webidl.spec.whatwg.org/#this).[[writable]] with its [writeAlgorithm](https://streams.spec.whatwg.org/#writablestream-set-up-writealgorithm) set to [writeEncodedData](https://w3c.github.io/webrtc-encoded-transform/#abstract-opdef-writeencodeddata) given this as parameter and its [sizeAlgorithm](https://streams.spec.whatwg.org/#writablestream-set-up-sizealgorithm) to an algorithm that returns 0.
>
>Chunk size is set to 0 to explictly disable streams backpressure on the write side.

https://github.com/w3c/webrtc-encoded-transform/pull/108 disabled it and added some notes, but the intention is not clear why it should be disabled. The note only says it's disables by letting sizeAlgorithm to return 0 (which I think it should set highWaterMark to Infinity instead).

**Comment by youennf** [comment]
> I think it should set highWaterMark to Infinity instead

We can do this.


As of why it is disabled, the principle is that the pipeline is a realtime pipeline where buffering should be very limited.
Backpressure should be handled either at input or at output by the UA.
For instance, if the writer is pushing data to the network, packets might be dropped if overshooting network, or the encoder will reduce the size of next frames to limit throughput.
In any case, backpressure should not be used to let the web applications delay its transform processing.

**Comment by alvestrand** [comment]
This is the wrong direction to go in.
Depending on the UA knowing how the input of the transform connects to the output of the transform is the wrong model, and needs to be abandoned; for one thing, it does not permit one-ended use cases.

The right way of approaching this is to make the feedback channel explicit as outlined in https://github.com/alvestrand/hackathon-encoded-media

Backpressure is a safety feature that limits the amount of trouble a transform can cause; it is not a good feature, but it is a needed one until we have the explicit feedback channels ready.
