### ISSUE TITLE
Security evaluation

### ISSUE THREAD

**Issue by youennf** [w3c/webrtc-encoded-transform#20]
This is a general issue about evaluating the security risks this new API can bring to existing infrastructure and adding a security section.

One potential threat is the following: by allowing JS to modify media content post-encoding, this API allows an attacker that is able to inject code in a page doing a WebRTC call to send RTP packets with poisoned content to either SFU or other participants in the call. Without this API, the attack is more difficult since the encoder will probably generate sanitised content. A non-browser attacker might be able to generate the same poisoned content but may not be able to connect easily to either SFU or other participants.

**Comment by fippo** [comment]
Such vulnerabilities already exist, see https://googleprojectzero.blogspot.com/2018/12/adventures-in-video-conferencing-part-1.html and the other parts of the series.

It is actually quite funny that one can write the fuzzer in JS now.

**Comment by youennf** [comment]
Right, I think the spec should acknowledge that this API exposing new parts of the WebRTC stack to an attacker, WebRTC implementations need to consider that some data that were previously trusted (say the output of an encoder) can no longer be trusted.
