### ISSUE TITLE
Frame packetization

### ISSUE THREAD

**Issue by AfonsoVilalonga** [w3c/webrtc-encoded-transform#233]
I have a question that is probably not entirely suitable for this repo, but I wasn't sure where else to ask it.

Basically, it seems that the maximum size of a VP8 frame that the browser (Google Chrome) can send before packetization is 1174 bytes, but I am not entirely sure why. 

I tested this by reading the RTP packets in a Pion application that are being received from a web browser application (Google Chrome) (the browser sends the frames, and Pion receives them). The size of the frame is manipulated using the WebRTC Encoded Transforms API, and for sizes greater than 1174 bytes, the frame is divided into two packets.

However, this doesn't make much sense to me, since the size of the RTP header being sent is 12 bytes (as seen in Wireshark), and 4 additional bytes are added to each packet for the VP8 payload descriptor. This means that the maximum size should be 1200 - (12 + 4) = 1184 bytes. Is there any insight I might be missing, or am I testing something incorrectly?

Thank you in advance for the help!

**Comment by alvestrand** [comment]
There's more overhead that comes into play in certain cases - RTP header extensions, TURN channel headers and so on. 
In order to not have to continuously reconfigure the packetizer, we configure the packet to be slightly smaller than the max.

**Comment by alvestrand** [comment]
BTW, the canonical place to ask Chrome webrtc implementation questions is discuss-webrtc@googlegroups.com

**Comment by AfonsoVilalonga** [comment]
Oh, okay, thank you so much, and sorry for not using the group!

Could I just ask one more question? What is the configured size of the packets?
