### ISSUE TITLE
Insertable MediaStreams in chrome issues

### ISSUE THREAD

**Issue by tato123** [w3c/webrtc-encoded-transform#38]
It may be unclear to me, however following the standard the following use cases are listed:

- Funny Hats (processing inserted before encoding or after decoding)
- Background removal
- Voice processing
- Dynamic control of codec parameters
- App-defined bandwidth distribution between tracks
- Custom codecs for special purposes (in combination with WebCodecs)

And the approach lists the standard as following the pattern of [WebCodecs](https://github.com/pthatcherg/web-codecs/). However, the current chrome 83 release does not seem to support converting the frame back to image data event though web codecs appears to. 

I've followed the example from the medooze blog article and posted the code in this repository https://github.com/tato123/face-detection-insertable-mediastreams. Note, within their example they are performing face detection using `createImageBitmap` from the video element and passing to an offscreen canvas. Currently there does not seem to be a way of directly accessing the image data from a frame.

I would like clarification on how the use cases for the standard could be implemented given the data provided within a stream

**Comment by aboba** [comment]
@tato123 I am assuming that the Medooze blog you are referring to is this one? https://levelup.gitconnected.com/adding-metadata-to-media-frames-via-insertable-streams-api-for-webrtc-47f7a740e457

**Comment by tato123** [comment]
@aboba yes, that's correct, apologies for not including the link

**Comment by aboba** [comment]
@tato123 As Sergio points out in the blog, we not yet have APIs to implement the ["funny hats"](https://w3c.github.io/webrtc-nv-use-cases/#funnyhats*) or ["machine learning"](https://w3c.github.io/webrtc-nv-use-cases/#machinelearning*) use cases with high performance. Insertable Streams does not yet provide access to raw video, and [WebCodecs](https://github.com/WICG/web-codecs) is still in its early stages.

There are several outstanding questions for both APIs: 
* Minimizing the performance impact of memory copies and garbage collection
* Integration with WebGPU

**Comment by tato123** [comment]
@aboba thank you for the clarification. I'll continue to watch the repository then for any updates.

**Comment by aboba** [comment]
@tato123 @alvestrand Would it be useful to discuss this at the July 8 WEBRTC WG Virtual Interim?  Slides are here:
https://docs.google.com/presentation/d/1rHXd5vxv_ME5r2TgpLPhJlD2iq0lcxQCsYbuT6fg0dc/

**Comment by tato123** [comment]
@aboba I believe it would be useful. It also looks like slide 49 links to the medooze blog article and partially touches on the use case I was attempting to perform (real time / video synced meta data based on video frame analysis)

**Comment by dontcallmedom** [comment]
https://github.com/w3c/mediacapture-transform is where work on raw media processing is happening, closing the issue here
