### ISSUE TITLE
Does transform receive Frames or Chunks?

### ISSUE THREAD

**Issue by boulos** [w3c/webrtc-encoded-transform#47]
Many of the examples here (as in the current explainer.md) have the signature:

 ```async transform(encodedFrame, controller)```

but assuming that this is really just Streams, isn't the original example from the slides (https://docs.google.com/presentation/d/1NIHzumglY9cYa4b7rcEbHGVsMam5BiY80VfFDB6cDjQ/edit#slide=id.g7eb1549726_1_10):

 ```async transform(chunk, controller)```

more accurate? That is, does InsertableStreams build up a full frame for arg0.data?

Nearly all online examples just overwrite / mess with all the bytes in a uniform way (e.g., bit complementing everything) that wouldn't whether arg0 was just a chunk or the full frame.

Maybe documenting what happens for a video stream in VP8 would be useful? https://github.com/w3c/webrtc-insertable-streams/issues/32#issuecomment-636032431 mentions that:

> It actually doesn't provide access to the full info of the RTP payload; the RTP headers and the segmenting that goes into putting frames into RTP packets isn't reflected in the Insertable Streams API.

But that note isn't reflected in either the spec (index.bs, correct?) nor explainer.md for "what actually goes into the ArrayBuffer data".

@alvestrand could you clarify this?

**Comment by lgrahl** [comment]
In general, the [Streams API](streams.spec.whatwg.org/) uses the term *chunk*. The meaning of *chunk* depends on the context. In this case I'm fairly certain what you're working with is an actual frame.

**Comment by fippo** [comment]
We renamed the generic "chunk" to "encodedFrame" a while back, see #16 and the PR linked from there.

> In this case I'm fairly certain what you're getting is a full (encoded) frame that will be encrypted by SRTP in the following step

Not quite, for VP8 there is the payload descriptor that is not part of the encoded frame. For H264 its a bit more complicated, adding the NAL header but stripping the start code.

**Comment by lgrahl** [comment]
Right. That emphasizes the point on "rather treat this as an opaque binary blob".

**Comment by dontcallmedom** [comment]
question was answered, closing the issue
