### ISSUE TITLE
Consider using TransformStreams instead of exposing ReadableStream/WritableStream

### ISSUE THREAD

**Issue by youennf** [w3c/webrtc-encoded-transform#48]
It might be worth considering using TransformStreams instead of exposing ReadableStream/WritableStream directly.
One reason is consistency with other APIs like https://encoding.spec.whatwg.org/#interface-textencoderstream or https://encoding.spec.whatwg.org/#interface-textencoderstream.
This for instance makes it easier to define native transforms.
Not dealing with ReadableStream is also nice to remove some potential foot guns like cloning a ReadableStream.

**Comment by youennf** [comment]
I updated a draft API at https://github.com/youennf/webrtc-insertable-streams/blob/modif/modifications.md along those lines for both a SFrame native transform as well as a script transform.

**Comment by alvestrand** [comment]
I don't believe this will serve use cases where the desired result is processing in a generic worker.

The GenericTransformStream is the inverse of the ReadableStream/WritableStream pair exposed by an RTCRtpSender/Receiver; the TransformStream does something to what's sent on its writable and emits it on its readable, while the RTCRtpSender/Receiver emits stuff on its readable and expects to have the transformed result on its writable.

In pluggable terms, TransformStream is the plug, and RTCRtpSender/Receiver is the socket.

**Comment by youennf** [comment]
I think this is fixed now with the introduction of SFrameTransform and RTCRtpScriptTransform.
Closing.
