### ISSUE TITLE
Optimizing encoded frame buffer allocation and memory copies

### ISSUE THREAD

**Issue by youennf** [w3c/webrtc-encoded-transform#49]
RTCEncodedAudioFrame and RTCEncodedVideoFrame both own an ArrayBuffer.
This array buffer is exposed to JavaScript by ReadableStream and consumed by WritableStream.

One important design API goal is to limit memory copies, maybe allow in-place transform of the array buffer so that there is no memory copy and no memory allocation.

One possibility would be to allow the frame array buffer to be detached after the frame is enqueued in the WritableStream.

**Comment by lgrahl** [comment]
Resolving #6 along the way would help a lot.

**Comment by youennf** [comment]
> Resolving #6 along the way would help a lot.

I guess something like https://github.com/domenic/proposal-arraybuffer-transfer could potentially help, I am unsure of the proposal status.
@domenic, @ricea, any thoughts on what would be the best practice here?

**Comment by lgrahl** [comment]
For #6, I was thinking less along the line of reallocating and then moving the data but more around defining where the frame data should be placed (headroom) and how much space should be at the end (legroom) which then requires no no copying or moving at all. A general API on `ArrayBuffer` that achieves this (perhaps a `ArrayBufferScheme`) would of course be cooler. :slightly_smiling_face:

**Comment by domenic** [comment]
For the readable stream, if you make it a readable byte stream, then you get all the reduced-copy mechanisms automatically.

For writable stream, you could transfer the array buffer the moment it is written to the underlying sink, which then allows the browser code to take ownership of the underlying data and use it directly. For this, you don't need the (mostly-defunct) https://github.com/domenic/proposal-arraybuffer-transfer, which is about exposing the primitive to JavaScript. Instead, you can do it on a spec/implementation level, using https://streams.spec.whatwg.org/#transfer-array-buffer

**Comment by alvestrand** [comment]
@domenic it is fundamental to this use case that the stream is a stream of frames, not a stream of bytes. So byte stream optimizations, apart from being sources of inspiration, are irrelevant here.

**Comment by youennf** [comment]
Closing based on the fact that the array buffer gets detached when enqueued.
