### ISSUE TITLE
Consider renaming to WebRTC Encoded Media Transform

### ISSUE THREAD

**Issue by jan-ivar** [w3c/webrtc-encoded-transform#61]
Two repos use the term _"insertable streams"_, this one and [w3c/mediacapture-insertable-streams](https://github.com/w3c/mediacapture-insertable-streams), causing a bit of confusion.

It might be better to name specs based on what they do, rather than on the shape of a particular solution, to distinguish them.

For this repo, maybe _"WebRTC Encoded Media Transform"_? Credit to @martinthomson https://github.com/w3c/webtransport/issues/174#issuecomment-744082461

**Comment by agouaillard-cosmo** [comment]
I believe this is an improvement.
+1

**Comment by youennf** [comment]
Sounds good to me as well

**Comment by youennf** [comment]
WebRTC encoded media has consensus amongst editors.

**Comment by youennf** [comment]
@dontcallmedom, what is needed to rename the title spec and repo name?

**Comment by youennf** [comment]
Proposed URL: webrtc-encoded-transform

**Comment by dontcallmedom** [comment]
title spec is a matter of updating the bikeshed file; I'll proceed with renaming the repository

**Comment by dontcallmedom** [comment]
for sake of clarity, do we really want "webrtc-encoded-transform" as repo name rather than "webrtc-encoded-media" given the spec title?

**Comment by youennf** [comment]
> for sake of clarity, do we really want "webrtc-encoded-transform" as repo name rather than "webrtc-encoded-media" given the spec title?

@alvestrand, any comment.
I feel like webrtc-encoded-media makes more sense given the name we want for the spec.

**Comment by alvestrand** [comment]
We'd like to have the transform in the shortname for symmetry with mediacapture-transform (see https://github.com/w3c/mediacapture-insertable-streams/issues/17). So I think we'd like to stay with webrtc-encoded-transform for the repo.

**Comment by youennf** [comment]
Latest consensus: rename to "WebRTC Encoded Transform" and webrtc-encoded-transforms

**Comment by youennf** [comment]
@dontcallmedom, can you rename the repo? I'll do a PR to change the title name

**Comment by dontcallmedom** [comment]
repo renamed
