### ISSUE TITLE
SFrameTransfor.setEncryptionKey cannot use all possible keyID values

### ISSUE THREAD

**Issue by youennf** [w3c/webrtc-encoded-transform#69]
As per SFrame, keyID can be 64 bits.
But unsigned long long is only mapping precisely up to 53 bits, as per https://heycam.github.io/webidl/#abstract-opdef-converttoint.

One possibility is to use a BigInt in lieu, or in addition maybe.
In that case values above max<unsigned long long> could trigger a RangeError.

**Comment by alvestrand** [comment]
If it's a 64-bit entity, where arithmetic makes no sense, I would think that we should represent it as a string of 4 bytes.

This is a case for the API advice gurus, I guess.

**Comment by youennf** [comment]
The proposal to keep unsigned long long is because it makes it handy to use with small incremented values.
This is the preferred approach for SFrame. But we should not preclude random values either.

Another possibility is to rely on Array/ArrayBuffer.
