### ISSUE TITLE
RTCInsertableStreams dictionary removed accidentally?

### ISSUE THREAD

**Issue by foolip** [w3c/webrtc-encoded-transform#72]
https://github.com/w3c/webrtc-insertable-streams/pull/62 removed the definition of `RTCInsertableStreams`, but it's still used as the return type of two methods in https://w3c.github.io/webrtc-insertable-streams/#specification.

@alvestrand was this an accident, or should the methods also be removed/tweaked?

**Comment by youennf** [comment]
This was an accident.
The direction is to remove these methods but we are not yet ready to do so.
