### ISSUE TITLE
what metadata is useful?

### ISSUE THREAD

**Issue by fippo** [w3c/webrtc-encoded-transform#9]
This API should enable cryptographic schemes to be built ontop of it. What we have at a bit lower level is [SRTP](https://tools.ietf.org/html/rfc3711#section-4.1.1) and [srtp + gcm](https://tools.ietf.org/html/rfc7714#section-8.1) which use input from the RTP packet.

I am not sure the [SSRC]((https://cs.chromium.org/chromium/src/third_party/blink/renderer/modules/peerconnection/rtc_encoded_video_frame.idl?type=cs&q=rtc_encoded_video_frame.idl&sq=package:chromium&g=0&l=23)) is always useful as some SFUs do ssrc rewriting so can not use it in their e2ee encryption scheme. Same goes for the pictureId and (rtp) timestamp. For simulcast rewriting pictureId towards the receiver is a must effectively.

Note that this just means that when using these as input for the IV or counter that IV/counter must still be sent along. For GCM I suspect that allowing the IV to be generated programatically and then sent alongside the packet would still be better than requiring the generation of a large number of (cryptographically?) random numbers.

**Comment by alvestrand** [comment]
crypto IV generation is well into crypto-land.
I know that you MUST NOT reuse an IV. But a large random number + a counter is apparently considered "good enough" in other cases. Yes, you need to send it along - otherwise, decoding a frame would require having counted all previous frames on that track accurately, which goes against what SFUs do best (lose frames).

**Comment by fippo** [comment]
Yes. SRTP gets around signaling the IV due to the fact that there are some things like the (extended) sequence number in the RTP header that allow reconstructing the IV. I would like something like that but I am not sure it is achievable at frame level - or that the solution would be less overhead than just sending the IV along.

The overhead for GCM + IV is 16+12 bytes respectively. For video frames that is ok. For audio it is a tad high but the length of the gcm authenticatio tag might be chosen shorter there, similar to the truncation to _32 for some SRTP cipher suites. Or one goes for a larger ptime.

**Comment by murillo128** [comment]
Those issues were discussed in detail in PERC group (and in later forums), the info in the rtp packet is not useful for e2ee and needs to be duplicated inside the packet (frame in this case) as most of it can(will) be changed by the SFU.

So, apart of the info required to demultiplex the frames to a particular encryption context (for example in simulcast, which may be solved by having one stream pair per encoding) and maybe the intra frame type for some optimizations in video flow.

**Comment by fippo** [comment]
also useful:
* kind (as in MediaStreamTrack.kind)
* codec/mimeType [as defined here](https://w3c.github.io/webrtc-stats/#dom-rtccodecstats-mimetype)
kind allows using the same encode/decode function for both audio and video instead of having two slightly different ones. Codec... allows codec-specific decisions.

**Comment by alvestrand** [comment]
A key part is the dependency chaining: when an MCU (or a sender) decides what frames to discard, it must know what that frame depends on - and ideally what future frames may depend on it, so that it can throw away those frames too.
Spatial and temporal layer indexes are one part of that puzzle.

**Comment by fippo** [comment]
ping. I'd still like to see the mimeType which may influence the encryption scheme.

**Comment by aboba** [comment]
@alvestrand @murillo128 We included both dependencies and chains in the WebCodecs metadata proposal (not yet merged):
https://docs.google.com/document/d/1O6kxAQPLWhCRHkH-6zutcqEUOUWRS6NFM2CQAvi1VTg/

The proposal is designed to include the same info as is provided by the AV1 Dependency Descriptor: 
https://aomediacodec.github.io/av1-rtp-spec/#dependency-descriptor-rtp-header-extension

**Comment by murillo128** [comment]
thanks @aboba I have already added some comments to the doc. 

any similar work has been done for audio metadata?

**Comment by fippo** [comment]
I think we're done with this one. More specific issues should be filed for stuff that is still missing
